name: WHen PR opened do this

on: 
 pull_request:
   types:
     - "closed"

jobs:
  Run_the_thing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
       teams_webhook_url: ${{ secrets.BeardTeams }}
       message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."