name: WHen PR opened do this

on: 
 pull_request:
   types:
     - "opened"

jobs:
  Run_the_thing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Run a command
      run: |
        Write-Host "What do we have?"
        $PRBody =  " We have - {0}" -f ${{ github.event.pull_request }}
        Write-Host $PRBody 
      shell: pwsh
      continue-on-error: true   
